name: Robot_SIG
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer les outils
        run: |
          pip install geopandas fiona pyproj

      - name: Lancer le traitement
        run: python traitement.py

      - name: Sauvegarder le résultat
        run: |
          git config --global user.name 'Robot-SIG'
          git config --global user.email 'robot@github.com'
          git add resultat.geojson
          git commit -m "Mise à jour automatique" || echo "Rien à changer"
          git push
