name: Robot_SIG
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Permet de le lancer à la main si besoin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v3

      - name: Installer Python et les outils
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installation Express
        run: pip install geopandas fiona pyproj

      - name: Lancer le script
        run: python traitement.py

      - name: Sauvegarder sur GitHub
        run: |
          git config --global user.name 'Robot-SIG'
          git config --global user.email 'robot@github.com'
          git add resultat.geojson
          git commit -m "MAJ Automatique par le robot" || echo "Rien à changer"
          git push
